# Generated by Django 5.1.2 on 2024-11-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('immatriculation', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('marque', models.CharField(max_length=50)),
                ('modele', models.CharField(max_length=50)),
                ('etat', models.CharField(max_length=20)),
            ],
        ),
    ]
